import type { TimelineEvent } from "@/types/event"

const events: TimelineEvent[] = [
  {
    id: "nolan-following",
    title: "Following",
    startDate: { year: 1998 },
    tags: ["art:movie:director:nolan"],
    counteries: ["us"],
    description: "Nolan's very first feature film",
    images: ["/images/nolan-following.png"],
  },
  {
    id: "nolan-memento",
    title: "Memento",
    startDate: { year: 2000 },
    tags: ["art:movie:director:nolan"],
    counteries: ["us"],
    images: ["/images/nolan-memento.png"],
  },
  {
    id: "nolan-insomnia",
    title: "Insomnia",
    startDate: { year: 2002 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-insomnia.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-batman-begins",
    title: "Batman Begins",
    startDate: { year: 2005 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-batman-begins.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-prestige",
    title: "Prestige",
    startDate: { year: 2006 },
    tags: ["art:movie:director:nolan"],
    counteries: ["us"],
  },
  {
    id: "nolan-the-dark-knight",
    title: "The Dark Knight",
    startDate: { year: 2008 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-the-dark-knight.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-inception",
    title: "Inception",
    startDate: { year: 2010 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-inception.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-the-dark-knight-rises",
    title: "The Dark Knight Rises",
    startDate: { year: 2012 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-the-dark-knight-rises.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-interstellar",
    title: "Interstellar",
    startDate: { year: 2014 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-interstellar.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-dunkirk",
    title: "Dunkirk",
    startDate: { year: 2017 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-dunkirk.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-tenet",
    title: "Tenet",
    startDate: { year: 2020 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-tenet.png"],
    counteries: ["us"],
  },
  {
    id: "nolan-oppenheimer",
    title: "Oppenheimer",
    startDate: { year: 2023 },
    tags: ["art:movie:director:nolan"],
    images: ["/images/nolan-oppenheimer.png"],
    counteries: ["us"],
  },
]

export default events
