export const countryNames: Record<string, string> = {
  af: "Afghanistan",
  ca: "Canada",
  cn: "China",
  eg: "Egypt",
  gb: "United Kingdom",
  in: "india",
  ir: "Iran",
  il: "Israil",
  iq: "Iraq",
  kz: "Kazakistan",
  jp: "Japan",
  no: "Norway",
  pk: "Pakistan",
  ru: "Russa",
  sa: "Saudi Arabia",
  sy: "Syria",
  tm: "Tajikestan",
  tr: "Turkey",
  ua: "Ukrain",
  us: "United States",
}
