import type { MapInfo } from "@/types/map"

export const MAPS: Record<string, MapInfo> = {
  blue: {
    id: "blue",
    name: "Blue",
    texture: "blue.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "blue.jpg",
    theme: "light",
  },
  night: {
    id: "night",
    name: "Night",
    texture: "night.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "night.jpg",
    theme: "dark",
  },
  aqua: {
    id: "aqua",
    name: "Aqua",
    texture: "aqua.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "aqua.jpg",
    theme: "light",
    countryBorderColor: "darkgray",
    atmosphereColor: "#78acc4",
    font: "Vend Sans, sans-serif",
  },
  atlas: {
    id: "atlas",
    name: "Atlas",
    texture: "atlas.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "atlas.jpg",
    theme: "light",
    countryBorderColor: "#4f4823",
    font: "EB Garamond, serif",
  },
  naturalEarthOcean: {
    id: "naturalEarthOcean",
    name: "Natural Earth Ocean",
    texture: "naturalEarthOcean.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "naturalEarthOcean.jpg",
    theme: "light",
  },
  hypsometricOcean: {
    id: "hypsometricOcean",
    name: "Hypsometric Ocean",
    texture: "hypsometricOcean.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "hypsometricOcean.gif",
    theme: "light",
  },
  naturalEarth: {
    id: "naturalEarth",
    name: "Natural Earth",
    texture: "naturalEarth.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "naturalEarth.jpg",
    theme: "light",
  },
  hypsometric: {
    id: "hypsometric",
    name: "Hypsometric",
    texture: "hypsometric.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "hypsometric.gif",
    theme: "light",
  },
  gray: {
    id: "gray",
    name: "Gray",
    texture: "gray.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "gray.jpeg",
    theme: "light",
  },
  prisma: {
    id: "prisma",
    name: "Prisma",
    texture: "prisma.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "prisma.jpeg",
    theme: "light",
  },
  shadedRelief: {
    id: "shadedRelief",
    name: "Shaded Relief",
    texture: "shadedRelief.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "shadedRelief.gif",
    theme: "light",
  },
  specular: {
    id: "specular",
    name: "Specular",
    texture: "specular.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "specular.jpg",
    theme: "light",
    countryBorderColor: "white",
  },
}

export const MAPS_LIST = Object.values(MAPS)
