import type { MapInfo } from "@/types/map"

export const MAPS: Record<string, MapInfo> = {
  hypsometric: {
    id: "hypsometric",
    name: "Hypsometric",
    texture: "hypsometric.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "hypsometric.gif",
    theme: "light",
  },
  hypsometricOcean: {
    id: "hypsometricOcean",
    name: "Hypsometric Ocean",
    texture: "hypsometricOcean.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "hypsometricOcean.gif",
    theme: "light",
  },
  naturalEarth: {
    id: "naturalEarth",
    name: "Natural Earth",
    texture: "naturalEarth.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "naturalEarth.jpg",
    theme: "light",
  },
  naturalEarthOcean: {
    id: "naturalEarthOcean",
    name: "Natural Earth Ocean",
    texture: "naturalEarthOcean.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "naturalEarthOcean.jpg",
    theme: "light",
  },
  night: {
    id: "night",
    name: "Night",
    texture: "night.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "night.jpg",
    theme: "dark",
  },
  shadedRelief: {
    id: "shadedRelief",
    name: "Shaded Relief",
    texture: "shadedRelief.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "shadedRelief.gif",
    theme: "light",
  },
  prisma: {
    id: "prisma",
    name: "Prisma",
    texture: "prisma.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "prisma.jpeg",
    theme: "light",
  },
  gray: {
    id: "gray",
    name: "Gray",
    texture: "gray.jpg",
    normalMap: "normalMap.jpg",
    heightMap: "heightMap.jpg",
    thumbnail: "gray.jpeg",
    theme: "light",
  },
}

export const MAPS_LIST = Object.values(MAPS)
