import { IranIcon } from "@/components/icons/iran"
import type { EventTag } from "@/types/event"
import {
  AtomIcon,
  BookIcon,
  BrainIcon,
  BrushIcon,
  CarFrontIcon,
  ChurchIcon,
  ClapperboardIcon,
  EarthIcon,
  Gamepad2Icon,
  MapPinIcon,
  MonitorIcon,
  MusicIcon,
  PaletteIcon,
  RocketIcon,
  ScrollTextIcon,
  TimerIcon,
  UserIcon,
  UsersIcon,
} from "lucide-react"

export const TAGS: EventTag[] = [
  {
    id: "history",
    name: "History",
    color: "oklch(76.9% 0.188 70.08)",
    icon: ScrollTextIcon,
  },
  {
    id: "history:human",
    name: "Human History",
    color: "oklch(76.9% 0.188 70.08)",
    icon: UsersIcon,
  },
  {
    id: "history:country",
    name: "Countries",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war",
    name: "Wars",
    color: "red",
    icon: CarFrontIcon,
  },
  {
    id: "history:war:crusade",
    name: "Crusades",
    color: "red",
    icon: EarthIcon,
  },
  {
    id: "history:war:ww1",
    name: "World War 1",
    color: "red",
    icon: EarthIcon,
  },
  {
    id: "history:war:ww2",
    name: "World War 2",
    color: "red",
    icon: EarthIcon,
  },
  {
    id: "history:war:vietnam",
    name: "Vietnam",
    color: "red",
    icon: EarthIcon,
  },
  {
    id: "history:war:israel-palastine",
    name: "israel - Palastine",
    color: "red",
    icon: EarthIcon,
  },
  {
    id: "history:war:iran-iraq",
    name: "Iran - Iraq",
    color: "red",
    icon: EarthIcon,
  },
  {
    id: "history:country:ir",
    name: "Iran",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:government",
    name: "Governance History",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:government:islamic-republic",
    name: "Islamic Republic",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:government:islamic-republic:crime",
    name: "Crimes",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:government:pahlavi-dynesty",
    name: "Pahlavi Dynesty",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:government:qajar-dynesty",
    name: "Qajar Dynesty",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:city",
    name: "Cities",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:ir:city:tehran",
    name: "Tehran",
    color: "oklch(69.6% 0.17 162.48)",
  },
  {
    id: "history:country:ir:city:mashhad",
    name: "Mashhad",
    color: "oklch(69.6% 0.17 162.48)",
  },
  {
    id: "history:country:ir:city:isfahan",
    name: "Isfahan",
    color: "oklch(69.6% 0.17 162.48)",
  },
  {
    id: "history:country:ir:city:shiraz",
    name: "Shiraz",
    color: "oklch(69.6% 0.17 162.48)",
  },
  {
    id: "history:country:us",
    name: "United States",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:ru",
    name: "Russia",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:ch",
    name: "China",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:gb",
    name: "United Kingdom",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:jp",
    name: "Japan",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:religion",
    name: "Religion",
    color: "brown",
    icon: ChurchIcon,
  },
  {
    id: "history:religion:islam",
    name: "Islam",
    color: "green",
    icon: ChurchIcon,
  },
  {
    id: "history:religion:christianity",
    name: "Christianity",
    color: "red",
    icon: ChurchIcon,
  },
  {
    id: "history:religion:jewish",
    name: "Jewish",
    color: "blue",
    icon: ChurchIcon,
  },
  {
    id: "knowledge",
    name: "Knowledge",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:cosmic",
    name: "Cosmic",
    color: "oklch(58.5% 0.233 277.117)",
    icon: EarthIcon,
  },
  {
    id: "knowledge:physics",
    name: "Physics",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:chemistry",
    name: "Chemistry",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:biology",
    name: "Biology",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:psychology",
    name: "Psychology",
    color: "oklch(58.5% 0.233 277.117)",
    icon: BrainIcon,
  },
  {
    id: "knowledge:technology",
    name: "Technology",
    color: "oklch(68.5% 0.169 237.323)",
    icon: MonitorIcon,
  },
  {
    id: "knowledge:space",
    name: "Space Exploration",
    color: "oklch(58.5% 0.233 277.117)",
    icon: RocketIcon,
  },
  {
    id: "art",
    name: "Art",
    color: "oklch(68.5% 0.169 237.323)",
    icon: PaletteIcon,
  },
  {
    id: "art:history",
    name: "Art History",
    color: "oklch(68.5% 0.169 237.323)",
    icon: PaletteIcon,
  },
  {
    id: "art:artist",
    name: "Artists",
    color: "oklch(64.5% 0.246 16.439)",
    icon: UserIcon,
  },
  {
    id: "art:music",
    name: "Music",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:history",
    name: "Music History",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band",
    name: "Bands",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:airbag",
    name: "Airbag",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:alice-in-chains",
    name: "Alice In Chains",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:anathema",
    name: "Anathema",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:archive",
    name: "Archive",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:black-sabbath",
    name: "Black Sabbath",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:camel",
    name: "Camel",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:nosound",
    name: "Nosound",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:pinkfloyd",
    name: "Pinkfloyd",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:radiohead",
    name: "Radiohead",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:tool",
    name: "TOOL",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:movie",
    name: "Movies",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:history",
    name: "Cinema History",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:director",
    name: "Directors",
    color: "oklch(63.7% 0.237 25.331)",
    icon: UserIcon,
  },
  {
    id: "art:movie:director:kubrick",
    name: "Stanley Kubrick",
    color: "oklch(63.7% 0.237 25.331)",
    icon: UserIcon,
  },
  {
    id: "art:movie:director:tarantino",
    name: "Quentin Tarantino",
    color: "oklch(63.7% 0.237 25.331)",
    icon: UserIcon,
  },
  {
    id: "art:movie:director:nolan",
    name: "Christopher Nolan",
    color: "oklch(63.7% 0.237 25.331)",
    icon: UserIcon,
  },
  {
    id: "art:painting",
    name: "Paintings",
    color: "oklch(63.7% 0.237 25.331)",
    icon: BrushIcon,
  },
  {
    id: "art:book",
    name: "Books",
    color: "oklch(63.7% 0.237 25.331)",
    icon: BookIcon,
  },
  {
    id: "art:game",
    name: "Video Games",
    color: "oklch(63.7% 0.237 25.331)",
    icon: Gamepad2Icon,
  },
  {
    id: "art:sport",
    name: "Sports",
    color: "oklch(63.7% 0.237 25.331)",
    icon: TimerIcon,
  },
]
