import { IranIcon } from "@/components/icons/iran"
import type { EventTag } from "@/types/event"
import {
  AtomIcon,
  BookIcon,
  BrainIcon,
  BrushIcon,
  ChurchIcon,
  ClapperboardIcon,
  EarthIcon,
  Gamepad2Icon,
  MapPinIcon,
  MonitorIcon,
  MusicIcon,
  PaletteIcon,
  ScrollTextIcon,
} from "lucide-react"

export const TAGS: EventTag[] = [
  {
    id: "knowledge",
    name: "Knowledge",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:cosmic",
    name: "Cosmic",
    color: "oklch(58.5% 0.233 277.117)",
    icon: EarthIcon,
  },
  {
    id: "knowledge:physics",
    name: "Physics",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:chemistry",
    name: "Chemistry",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:biology",
    name: "Biology",
    color: "oklch(58.5% 0.233 277.117)",
    icon: AtomIcon,
  },
  {
    id: "knowledge:psychology",
    name: "Psychology",
    color: "oklch(58.5% 0.233 277.117)",
    icon: BrainIcon,
  },
  {
    id: "knowledge:technology",
    name: "Technology",
    color: "oklch(68.5% 0.169 237.323)",
    icon: MonitorIcon,
  },
  {
    id: "history",
    name: "History",
    color: "oklch(76.9% 0.188 70.08)",
    icon: ScrollTextIcon,
  },
  {
    id: "history:country",
    name: "Countries",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war",
    name: "Wars",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war:crusade",
    name: "Crusades",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war:ww1",
    name: "World War 1",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war:ww2",
    name: "World War 2",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war:vietnam",
    name: "Vietnam",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war:israel-palastine",
    name: "israel - Palastine",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:war:iran-iraq",
    name: "Iran - Iraq",
    color: "oklch(69.6% 0.17 162.48)",
    icon: EarthIcon,
  },
  {
    id: "history:country:iran",
    name: "Iran",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:iran:government",
    name: "Governance History",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:iran:government:islamic-republic",
    name: "Islamic Republic",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:iran:government:islamic-republic:crime",
    name: "Crimes",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:iran:government:pahlavi-dynesty",
    name: "Pahlavi Dynesty",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:iran:government:qajar-dynesty",
    name: "Qajar Dynesty",
    color: "oklch(69.6% 0.17 162.48)",
    icon: IranIcon,
  },
  {
    id: "history:country:usa",
    name: "United States",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:russia",
    name: "Russia",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:china",
    name: "China",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:uk",
    name: "United Kingdom",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:country:japan",
    name: "Japan",
    color: "oklch(69.6% 0.17 162.48)",
    icon: MapPinIcon,
  },
  {
    id: "history:religion",
    name: "Religion",
    color: "oklch(69.6% 0.17 162.48)",
    icon: ChurchIcon,
  },
  {
    id: "history:religion:islam",
    name: "Islam",
    color: "oklch(69.6% 0.17 162.48)",
    icon: ChurchIcon,
  },
  {
    id: "history:religion:christianity",
    name: "Christianity",
    color: "oklch(69.6% 0.17 162.48)",
    icon: ChurchIcon,
  },
  {
    id: "history:religion:jewish",
    name: "Jewish",
    color: "oklch(69.6% 0.17 162.48)",
    icon: ChurchIcon,
  },
  {
    id: "art",
    name: "Art",
    color: "oklch(68.5% 0.169 237.323)",
    icon: PaletteIcon,
  },
  {
    id: "art:music",
    name: "Music",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:history",
    name: "Music History",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band",
    name: "Bands",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:pinkfloyd",
    name: "Pinkfloyd",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:tool",
    name: "TOOL",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:archive",
    name: "Archive",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:music:band:radiohead",
    name: "Radiohead",
    color: "oklch(64.5% 0.246 16.439)",
    icon: MusicIcon,
  },
  {
    id: "art:movie",
    name: "Movies",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:history",
    name: "Cinema History",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:director",
    name: "Directors",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:director:kubric",
    name: "Stanley Kubric",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:director:tarantino",
    name: "Quentin Tarantino",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:movie:director:nolan",
    name: "Christopher Nolan",
    color: "oklch(63.7% 0.237 25.331)",
    icon: ClapperboardIcon,
  },
  {
    id: "art:painting",
    name: "Paintings",
    color: "oklch(63.7% 0.237 25.331)",
    icon: BrushIcon,
  },
  {
    id: "art:book",
    name: "Books",
    color: "oklch(63.7% 0.237 25.331)",
    icon: BookIcon,
  },
  {
    id: "art:game",
    name: "Video Games",
    color: "oklch(63.7% 0.237 25.331)",
    icon: Gamepad2Icon,
  },
]
